/// <reference types="vite/client" />
declare const __MAX_TEXTAREA_LENGTH__: number;
declare const __MAX_INPUT_LENGTH__: number;
declare const __MAX_MULTI_FORM_COUNT__: number;
declare const __DEFAULT_INPUT_PLACEHOLDER__: string;
declare const __DEFAULT_TEXTAREA_PLACEHOLDER__: string;
declare const __DEFAULT_SELECT_PLACEHOLDER__: string;
declare const __DEFAULT_JSON_PLACEHOLDER__: string;
declare const __MAX_FLOW_NAME_LENGTH__: number;
declare const __HTTP_URL__: string;
